theme: jekyll-theme-minimal
title: Jennifer Senta, PhD
description: Postdoctoral Scholar Helen Wills Neuroscience Institute @UCBerkeley
logo: https://pbs.twimg.com/profile_images/1382497008091467778/e6UTvqKK_400x400.jpg
show_downloads: false
