theme: jekyll-theme-minimal
title: Jennifer Senta
description: PhD Candidate, Cognitive Neuroscience @UCBerkeley
logo: https://pbs.twimg.com/profile_images/1382497008091467778/e6UTvqKK_400x400.jpg
show_downloads: false
